#global vars
ci_cd_namespace: &ci_cd "cnp-ci-cd"

source: https://github.com/thegusmao/helm-provision-infra-cicd-test.git
namespace: cnp-ci-cd
# App of applications list
applications:
  # Nexus
  - destination: *ci_cd
    name: nexus
    enabled: true
    source: https://redhat-cop.github.io/helm-charts
    chart_name: sonatype-nexus
    source_ref: "1.1.4"
    values:
      service:
        name: nexus
  # Sonarqube
  - destination: *ci_cd
    name: sonarqube
    enabled: true
    source: https://redhat-cop.github.io/helm-charts
    chart_name: sonarqube
    source_ref: "0.1.1"
    values:
      # if integrating into an existing sealed secret or other cluster secret 
      # account:
      #   existingSecret: sonarqube-auth
      initContainers: true
      plugins:
        install:
          - https://github.com/checkstyle/sonar-checkstyle/releases/download/8.40/checkstyle-sonar-plugin-8.40.jar
          - https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/2.0.8/sonar-dependency-check-plugin-2.0.8.jar
  # Microcks
  - destination: microcks
    name: microcks
    enabled: false
    source: https://github.com/rht-labs/refactored-adventure
    source_path: microcks/base
    source_ref: master